version: "3.5"
services:
  nginx-api:
    build:
        dockerfile: blazefind-nginx-api
        context: .
    volumes:
    - ./api:/var/www/html
    ports:
    - "80"
    links:
    - php
  php:
    build:
        dockerfile: blazefind-php
        context: .
    volumes:
    - ./api:/var/www/html
    - /:/host
    links:
    - mysql
    - elasticsearch
  frontend:
    build:
        dockerfile: blazefind-nginx-frontend
        context: .
    volumes:
    - ./frontend:/var/www/html
    ports:
    - "80"
  mysql:
    image: mysql:8
    ports:
    - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: blazefind
      MYSQL_ROOT_PASSWORD: secret
  kibana:
    image: kibana:7.9.1
    ports:
    - "5601:5601"
  elasticsearch:
    environment:
    - discovery.type=single-node
    - node.name=es01
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    build:
        dockerfile: blazefind-elastic
        context: .
    ports:
    - "9200:9200"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
